<?php

define('HOT_BOOTSTRAP_DOCS_TEMPLATES', 'templates');


/**
 * Implements hook_menu().
 */
function hot_bootstrap_docs_menu() {
  $items = array();

  $items['bootstrap-docs'] = array(
    'title' => 'Theme Tests',
    'description' => 'Pages demonstrating widgets and molecular components of the site build',
    'type' => MENU_NORMAL_ITEM, // so the path is available in the menu tree
    'access arguments' => array('administer nodes'), // should get inherited by tabs
    'page callback' => 'theme',
    'page arguments' => array('typography_test_page'), // this should change. We should have intro text
  );

  $items['bootstrap-docs/css'] = array(
    'title' => 'Bootstrap Base CSS',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'theme',
    'page arguments' => array('bootstrap_css'),
    'access arguments' => array('administer nodes'),
    'weight' => '-6',
  );
  $items['bootstrap-docs/components'] = array(
    'title' => 'Bootstrap Components',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'theme',
    'page arguments' => array('bootstrap_components'),
    'access arguments' => array('administer nodes'),
    'weight' => '-5',
  );
  $items['bootstrap-docs/js'] = array(
    'title' => 'Bootstrap JavaScript',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'theme',
    'page arguments' => array('bootstrap_js'),
    'access arguments' => array('administer nodes'),
    'weight' => '-4',
  );

  $items['bootstrap-docs/typography'] = array(
    'title' => 'Typography',
    'weight' => '-1',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'page callback' => 'theme',
    'page arguments' => array('typography_test_page'),
    'access arguments' => array('administer nodes'),
    'weight' => '-1',
  );

  return $items;
}

/**
 * Implements hook_libraries_info().
 *
 * For defining external libraries.
 */

function hot_bootstrap_docs_libraries_info() {
  // Expected to be extracted into 'sites/all/libraries/simple'.
  $libraries['bootstrap_docs'] = array(
    'name' => 'Hot Bootstrap Docs',
    'vendor url' => 'http://getbootstrap.com',
    'download url' => 'http://getbootstrap.com/getting-started/',
    'path' => 'assets',
    'version callback' => '_hot_bootstrap_docs_version',
    'files' => array(
      'css' => array(
        'css/docs.min.css' => array(),
      ),
      'js' => array(
        'js/docs.min.js' => array(),
        'js/customize.min.js' => array(),
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_theme().
 */
function hot_bootstrap_docs_theme() {
  $items = array();

  $items['bootstrap_css'] = array(
    'template' => HOT_BOOTSTRAP_DOCS_TEMPLATES . '/bootstrap-css'
  );
  $items['bootstrap_components'] = array(
    'template' => HOT_BOOTSTRAP_DOCS_TEMPLATES . '/bootstrap-components'
  );
  $items['bootstrap_js'] = array(
    'template' => HOT_BOOTSTRAP_DOCS_TEMPLATES . '/bootstrap-js'
  );

  $items['typography_test_page'] = array(
    'template' => HOT_BOOTSTRAP_DOCS_TEMPLATES . '/typography-test-page',
  );

  return $items;
}

/**
 * Implements hook_preprocess_bootstrap_css.
 */
function hot_bootstrap_docs_preprocess_bootstrap_css(&$vars){
  _hot_bootstrap_docs_load_library();
}

/**
 * Implements hook_preprocess_bootstrap_components.
 */
function hot_bootstrap_docs_preprocess_bootstrap_components(&$vars){
  _hot_bootstrap_docs_load_library();
}

/**
 * Implements hook_preprocess_bootstrap_js.
 */
function hot_bootstrap_docs_preprocess_bootstrap_js(&$vars){
  _hot_bootstrap_docs_load_library();
}

/**
 * Load the bootstrap_docs library.
 */
function _hot_bootstrap_docs_load_library(){
  $bs_library = libraries_load('bootstrap_docs');
  if (empty($bs_library)) {
    drupal_set_message('The Bootstrap docs library could not be loaded', 'error');
  }
}

// Hotwire the library version for now.
// TODO learn regex.
function _hot_bootstrap_docs_version(){
  return TRUE;
}